Boolean conditional operator

In [8]:
import numpy as np

In [9]:
data1 = np.array([1.2, 2.8, 3.8, 4.7])
data2 = np.array([2.5, 7.8, 4.2, 8.9])

In [10]:
data1

array([1.2, 2.8, 3.8, 4.7])

In [11]:
data2

array([2.5, 7.8, 4.2, 8.9])

In [12]:
condition = np.array([True, False, False,True])

In [13]:
result = np.where(condition, data1, data2)
result

array([1.2, 7.8, 4.2, 4.7])

In [14]:
data3 = np.random.randn(6,6)
data3

array([[ 0.45483503,  0.54334154, -1.23788373, -0.81557132, -1.06057194,
         1.45736656],
       [ 0.5041113 ,  0.37695037, -0.43733632,  0.35475705,  0.00871929,
        -0.82960778],
       [-0.4151175 , -1.17670133,  2.10344836, -0.97980881,  0.82792019,
         0.87042653],
       [-0.5992459 ,  0.15206512, -0.00563015,  0.6878866 , -0.44103081,
         0.35550185],
       [-0.52330399,  0.60794863, -0.97147904, -1.00227399, -0.80067301,
         0.21712302],
       [ 0.74976899, -0.40208238, -1.91382639, -0.21885254,  2.13943651,
        -0.18396996]])

In [15]:
results = np.where(data3 < 0, -2, 2)
results

array([[ 2,  2, -2, -2, -2,  2],
       [ 2,  2, -2,  2,  2, -2],
       [-2, -2,  2, -2,  2,  2],
       [-2,  2, -2,  2, -2,  2],
       [-2,  2, -2, -2, -2,  2],
       [ 2, -2, -2, -2,  2, -2]])