Changing the axis of the array

In [19]:
import numpy as np


In [20]:
data = np.arange(6).reshape(3, 2)
data


array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
data.T

array([[0, 2, 4],
       [1, 3, 5]])

In [23]:
data.swapaxes(1,0)

array([[0, 2, 4],
       [1, 3, 5]])

In [24]:
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
np.dot(data, data.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])