Indexing and Cropping


In [26]:
import numpy as np

In [27]:
my_arry = np.arange(10, 100, 10)
my_arry

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
my_arry[:2]

array([10, 20])

In [29]:
my_2Darray = np.array([[1, 2, 3], [4, 5, 6]])
my_2Darray

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
my_2Darray[0, 0:2]

array([1, 2])

In [31]:
my_arry2 = np.arange(10, 100, 10)
my_arry2


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
cutting_array = my_arry2[3:5].copy()
cutting_array

array([40, 50])

In [33]:
arry_3d = np.array(
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
        [[19, 20, 21], [22, 23, 24], [25, 26, 27]],
    ]
)

In [34]:
arry_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [35]:
arry_3d.ndim

3

In [36]:
cutting = arry_3d[0][1, 1]
cutting

5

In [37]:
arry_3d[1][2, 1:]

array([17, 18])