Logical indexing


In [6]:
import numpy as np

In [7]:
names = np.array(['John', 'Smith', 'Tate', 'Smith','Mark', 'Adrew', 'Jorj'])
names

array(['John', 'Smith', 'Tate', 'Smith', 'Mark', 'Adrew', 'Jorj'],
      dtype='<U5')

In [8]:
random_data = np.random.randn(7,4)
random_data

array([[-0.59702731, -0.41696713,  0.71192093, -0.74757964],
       [ 0.59840187, -0.17898146,  1.22799626, -1.22544405],
       [-0.3492153 ,  0.64459501, -0.10263731,  0.01025454],
       [-0.70303709,  0.40718038, -0.63185175, -1.4102229 ],
       [-1.49786091,  0.34287008, -1.48379712,  0.23536925],
       [ 0.65140689, -0.40392048, -0.66935099,  2.05151354],
       [ 0.68572059,  0.62897304,  0.16505565, -0.38382515]])

In [9]:
names == 'John'

array([ True, False, False, False, False, False, False])

In [11]:
random_data[names == 'John']

array([[-0.59702731, -0.41696713,  0.71192093, -0.74757964]])

In [12]:
random_data[names == 'Smith']

array([[ 0.59840187, -0.17898146,  1.22799626, -1.22544405],
       [-0.70303709,  0.40718038, -0.63185175, -1.4102229 ]])

In [13]:
random_data[names == 'Tate', :2]

array([[-0.3492153 ,  0.64459501]])

In [23]:
print(names)
print(random_data)

['John' 'Smith' 'Tate' 'Smith' 'Mark' 'Adrew' 'Jorj']
[array([False,  True,  True,  True,  True,  True,  True])]


In [22]:
mask = (names == "John") | (names == "Smith")
mask

array([ True,  True, False,  True, False, False, False])

In [ ]:
random_data[mask]