Mathematical and Statistical operations


In [14]:
import numpy as np

In [15]:
data = np.random.rand(5,6)

In [16]:
data

array([[0.86571991, 0.10146422, 0.84516596, 0.64704928, 0.50539744,
        0.37715017],
       [0.11335366, 0.43961489, 0.14769028, 0.03400647, 0.21907385,
        0.77085908],
       [0.14810476, 0.71833338, 0.43952846, 0.88601392, 0.57028417,
        0.76819515],
       [0.46602044, 0.37128324, 0.76570002, 0.81923919, 0.86458699,
        0.88800486],
       [0.43689265, 0.7475998 , 0.86732185, 0.79137245, 0.34456697,
        0.52605318]])

In [17]:
data.sum()

16.48564670924584

In [18]:
np.sum(data)

16.48564670924584

In [19]:
data.sum(axis=0)

array([2.03009142, 2.37829553, 3.06540657, 3.17768132, 2.50390942,
       3.33026244])

In [20]:
data.sum(axis=1)

array([3.34194697, 1.72459823, 3.53045986, 4.17483474, 3.71380691])

In [21]:
data2 = np.arange(6)
data2

array([0, 1, 2, 3, 4, 5])

In [22]:
result = data2.sum()/len(data2)
result

2.5

In [23]:
np.mean(data2)

2.5

In [25]:
np.mean(data, axis=1)

array([0.55699116, 0.28743304, 0.58840998, 0.69580579, 0.61896782])

In [26]:
data2

array([0, 1, 2, 3, 4, 5])

In [27]:
data2.cumsum()

array([ 0,  1,  3,  6, 10, 15])

In [29]:
np.cumsum(data2)

array([ 0,  1,  3,  6, 10, 15])

In [2]:
arr  = np.array([0, 1, 2, 3])
n = np.cumsum(arr)
n

NameError: name 'np' is not defined