Numpy Arrays

In [87]:
import numpy as np

In [103]:
my_data = [12,12,15,151,15]

nump_arry = np.array(my_data)
nump_arry

array([ 12,  12,  15, 151,  15])

In [104]:
my_data2 = (12, 78, 945, 215, 445, 4)

nump_arry2 = np.array(my_data2)

nump_arry2

array([ 12,  78, 945, 215, 445,   4])

In [105]:
my_data3 = [[12, 7895, 56, 45, 87, 87], [12, 7895, 56, 45, 87, 87]]

nump_arry3 = np.array(my_data3)
nump_arry3

array([[  12, 7895,   56,   45,   87,   87],
       [  12, 7895,   56,   45,   87,   87]])

In [106]:
my_data4 = [[1, 2, 3, 4, 56], [1, 2, 3, 4, 56], [1, 2, 3, 4, 56]]

nump_arry4 = np.array(my_data4)

nump_arry4

array([[ 1,  2,  3,  4, 56],
       [ 1,  2,  3,  4, 56],
       [ 1,  2,  3,  4, 56]])

In [107]:
nump_arry.ndim

1

In [108]:
nump_arry3.ndim

2

In [109]:
nump_arry4.ndim

2

In [110]:
nump_arry4.size

15

In [111]:
nump_arry4.shape

(3, 5)

In [112]:
my_data5 = np.zeros((2,7))
my_data5

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [113]:
my_data6 = np.ones((5,8))
my_data6

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [114]:
my_data7 = np.arange(4,20,3)
my_data7

array([ 4,  7, 10, 13, 16, 19])

In [115]:
my_data8 = np.arange(21)
my_data8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [116]:
my_data9 = np.random.rand(2,4)
my_data9

array([[0.02741324, 0.30634708, 0.6829872 , 0.84422529],
       [0.08896305, 0.2542926 , 0.54060238, 0.65596237]])

In [117]:
my_data10 = np.random.randint(6, size=(4,4))
my_data10

array([[1, 0, 1, 2],
       [4, 2, 1, 2],
       [3, 3, 2, 5],
       [1, 5, 2, 5]])