Numpy Data Types

In [24]:
import numpy as np

In [25]:
my_data = np.array((12, 21, 25, 1), dtype=np.float32)
my_data

array([12., 21., 25.,  1.], dtype=float32)

In [26]:
my_data2 = np.array((12, 21, 25, 1), dtype=np.int32)
my_data2

array([12, 21, 25,  1])

In [27]:
my_data.dtype

dtype('float32')

In [28]:
my_data2.dtype

dtype('int32')

In [29]:
change_arry_type_float = my_data2.astype(np.float16)
change_arry_type_float

array([12., 21., 25.,  1.], dtype=float16)

In [21]:
float_number = np.array((1.8, 8.9, 6.7))
float_number

dtype('float64')

In [22]:
change_arry_type_int = float_number.astype(np.int32)
change_arry_type_int

array([1, 8, 6])

In [23]:
change_arry_type_int.dtype

dtype('int32')