Sorting

In [16]:
import numpy as np

In [17]:
data = np.random.randn(6)
data

array([-0.07946516,  0.71990836,  0.31861338, -0.32761224, -0.22612586,
        0.3458959 ])

In [18]:
sort = np.sort(data)
sort

array([-0.32761224, -0.22612586, -0.07946516,  0.31861338,  0.3458959 ,
        0.71990836])

In [19]:
resort = -np.sort(-data)
resort

array([ 0.71990836,  0.3458959 ,  0.31861338, -0.07946516, -0.22612586,
       -0.32761224])

In [20]:
data2 = np.random.randn(6,2)
data2

array([[-0.31503662, -0.87335789],
       [ 0.60700739,  1.22430416],
       [-0.26536243, -0.21839657],
       [-0.49387386,  0.133016  ],
       [-1.34924582,  1.41261148],
       [-0.63103968, -0.1495502 ]])

In [23]:
row_sorted = np.sort(data2, axis=1)
row_sorted

array([[-0.87335789, -0.31503662],
       [ 0.60700739,  1.22430416],
       [-0.26536243, -0.21839657],
       [-0.49387386,  0.133016  ],
       [-1.34924582,  1.41261148],
       [-0.63103968, -0.1495502 ]])