Universal functions


In [1]:
import numpy as np

In [2]:
data = np.arange(20)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
np.sqrt(data)  # returns the square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [4]:
np.square(data)  # returns a square

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [5]:
np.exp(data)  # returns expo

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [7]:
np.log(data[1:])  # returns natural logarithm

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [8]:
data1 = np.random.randn(10)
data1

array([ 0.2795369 , -0.897417  ,  0.40303198,  0.28727808,  0.00758433,
        1.53007512, -0.74047015,  0.54191798, -0.52151189,  0.49940039])

In [9]:
whole, rest = np.modf(data1)

In [11]:
print("Whote value", whole)
print("Rest Value", rest)

Whote value [ 0.2795369  -0.897417    0.40303198  0.28727808  0.00758433  0.53007512
 -0.74047015  0.54191798 -0.52151189  0.49940039]
Rest Value [ 0. -0.  0.  0.  0.  1. -0.  0. -0.  0.]


In [12]:
np.sign(data1)

array([ 1., -1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1.])

In [13]:
np.isnan(data1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [19]:
data1[0:3] = np.NaN
np.isnan(data1)

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [20]:
data2 = np.random.randn(25)
data3 = np.random.randn(25)

In [21]:
data2

array([ 0.9102279 ,  0.55220061, -1.7134605 ,  0.92824669, -0.4028418 ,
        0.46712098, -1.23389187,  0.22606717,  1.11260177, -0.95080235,
       -0.83449396,  0.47582661,  0.5895216 ,  0.26840241,  0.88702279,
       -0.00563609, -1.2990705 , -0.2527497 ,  1.03412568,  2.15389147,
       -0.04100584,  1.85472256,  0.2812146 , -0.35844283, -0.03932195])

In [22]:
data3

array([-0.66655342,  0.86348327, -1.17720556,  1.32845703,  1.08273888,
       -1.66663393, -0.10106194, -1.06906041,  0.98703202, -0.65199475,
        0.58796173, -0.66700939, -0.5010197 ,  0.00425111,  0.25085055,
       -0.92708035, -0.01538359, -0.4836015 ,  0.50153134,  1.60223862,
        1.02306909,  1.64983783,  0.23003431,  0.64922367,  0.0385015 ])

In [23]:
np.add(data3, data2)

array([ 2.43674474e-01,  1.41568388e+00, -2.89066606e+00,  2.25670373e+00,
        6.79897077e-01, -1.19951295e+00, -1.33495381e+00, -8.42993247e-01,
        2.09963380e+00, -1.60279710e+00, -2.46532232e-01, -1.91182779e-01,
        8.85018928e-02,  2.72653521e-01,  1.13787334e+00, -9.32716440e-01,
       -1.31445409e+00, -7.36351194e-01,  1.53565702e+00,  3.75613010e+00,
        9.82063248e-01,  3.50456039e+00,  5.11248904e-01,  2.90780838e-01,
       -8.20448829e-04])

In [24]:
np.multiply(data3, data2)

array([-6.06715523e-01,  4.76815987e-01,  2.01709522e+00,  1.23313585e+00,
       -4.36172484e-01, -7.78519679e-01,  1.24699508e-01, -2.41679458e-01,
        1.09817358e+00,  6.19918138e-01, -4.90650515e-01, -3.17380813e-01,
       -2.95361934e-01,  1.14100795e-03,  2.22510157e-01,  5.22510440e-03,
        1.99843721e-02,  1.22230132e-01,  5.18646436e-01,  3.45104811e+00,
       -4.19518125e-02,  3.05999145e+00,  6.46890050e-02, -2.32709574e-01,
       -1.51395377e-03])

In [25]:
np.maximum(data3, data2)

array([ 0.9102279 ,  0.86348327, -1.17720556,  1.32845703,  1.08273888,
        0.46712098, -0.10106194,  0.22606717,  1.11260177, -0.65199475,
        0.58796173,  0.47582661,  0.5895216 ,  0.26840241,  0.88702279,
       -0.00563609, -0.01538359, -0.2527497 ,  1.03412568,  2.15389147,
        1.02306909,  1.85472256,  0.2812146 ,  0.64922367,  0.0385015 ])