Working with files

In [12]:
import numpy as np

In [13]:
data = np.arange(15)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
saved = np.save('data', data)

In [15]:
data2 = np.arange(30)
data2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
saved2 = np.savez('data2', a=data, b=data2)

In [18]:
data3 = np.load('data.npy')
data3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])